// Generated by CoffeeScript 1.6.2
(function() {
  var delay, puts, smog;

  $(function() {
    return $(".smogbuttons > button").on("click", function() {
      $(this).attr("disabled", "true");
      $(this).siblings().removeAttr("disabled");
      return smog($(this).text());
    });
  });

  puts = function(str) {
    return console.log(str);
  };

  delay = function(s, func) {
    return setTimeout(func, s * 1000);
  };

  smog = function(action) {
    if (action === "fade in smog") {
      $("#smoglayer").addClass("smoggy fadeIn");
      return delay(1, function() {
        return $("#smoglayer").removeClass("fadeIn");
      });
    } else if (action === "fade out smog") {
      $("#smoglayer").addClass("fadeOut");
      return delay(1, function() {
        return $("#smoglayer").removeClass("fadeOut smoggy");
      });
    }
  };

}).call(this);
