// Generated by CoffeeScript 1.6.2
(function() {
  var delay, puts, smog;

  $(function() {
    var n, slides;

    n = 0;
    slides = $(".slide");
    $("nav > button").on("click", function() {
      var dir, slide, year;

      $("#slide" + n).hide();
      dir = $(this).attr("id");
      if (dir === "next") {
        if (!(n >= slides.length - 1)) {
          n++;
        }
      } else if (dir === "prev") {
        if (!(n <= 1)) {
          n--;
        }
      }
      slide = $("#slide" + n);
      slide.show();
      year = slide.attr("year");
      $("#year").text(year);
      return document.title = "(" + n + "/" + (slides.length - 1) + ") Earth Day";
    });
    $("#next").click();
    $(".smogbuttons > button").on("click", function() {
      $(this).attr("disabled", "true");
      $(this).siblings().removeAttr("disabled");
      return smog($(this).text());
    });
    return $("html").keyup(function(event) {
      var key;

      key = event.which;
      if (key === 37) {
        $("#prev").click();
      }
      if (key === 39) {
        return $("#next").click();
      }
    });
  });

  puts = function(str) {
    return console.log(str);
  };

  delay = function(s, func) {
    return setTimeout(func, s * 1000);
  };

  smog = function(action) {
    if (action === "clean air") {
      $(".effects").children().addClass("fadeOut");
      return delay(1, function() {
        return $(".effects").children().removeClass("fadeOut smog pollution");
      });
    } else if (action === "smoggy air") {
      $("#smog").addClass("smog fadeIn");
      delay(1, function() {
        return $("#smog").removeClass("fadeIn");
      });
      $("#pollution").addClass("fadeOut");
      return delay(1, function() {
        return $("#pollution").removeClass("pollution");
      });
    } else if (action === "pollution") {
      $("#smog").addClass("smog fadeIn");
      delay(1, function() {
        return $("#smog").removeClass("fadeIn");
      });
      $("#data").addClass("pollution animated fadeIn");
      $("#pollution").addClass("pollution fadeIn");
      return delay(1, function() {
        return $("#pollution").removeClass("fadeIn");
      });
    }
  };

}).call(this);
