// Generated by CoffeeScript 1.6.2
(function() {
  var delay, puts;

  $(function() {
    return $(".smogbuttons > button").on("click", function() {
      $(this).attr("disabled", "true");
      puts($(this).siblings().removeAttr("disabled"));
      if ($(this).text() === "fade in smog") {
        $("#smoglayer").addClass("smoggy fadeIn");
        return delay(1, function() {
          return $("#smoglayer").removeClass("fadeIn");
        });
      } else if ($(this).text() === "fade out smog") {
        $("#smoglayer").addClass("fadeOut");
        return delay(1, function() {
          return $("#smoglayer").removeClass("fadeOut smoggy");
        });
      }
    });
  });

  puts = function(str) {
    return console.log(str);
  };

  delay = function(s, func) {
    return setTimeout(func, s * 1000);
  };

}).call(this);
